### ISSUE TITLE
Window10 运行闪退？

### ISSUE THREAD

**Issue by solomon262** [xxzl0130/AntiRivercrab#1]
大佬好，我尝试着运行 Build-win.bat 文件，但是该文件直接闪退。尝试过使用管理员模式与兼容模式，无果。请问我是否需要下载golang通过go run指令去运行？

**Comment by xxzl0130** [comment]
你要用的话，在release页面下载发布的包就可以了，不需要源码发自我的华为手机-------- 原始邮件 --------发件人： solomon262 <notifications@github.com>日期： 2019年9月4日周三 11:45收件人： xxzl0130/AntiRivercrab <AntiRivercrab@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [xxzl0130/AntiRivercrab] Window10 运行闪退？ (#1)大佬好，我尝试着运行 Build-win.bat 文件，但是该文件直接闪退。尝试过使用管理员模式与兼容模式，无果。请问我是否需要下载golang通过go run指令去运行？

**Comment by solomon262** [comment]
谢谢，我去试试
